version: 2.1

orbs:
  node: circleci/node@5.0.3
  gh: circleci/github-cli@2.1.1

jobs:
  build-resources:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - gh/install
      - run:
          name: Package install
          command: npm install
      - run:
          name: Build all resources
          command: node index.js
      - run:
          name: Check generated files
          command: ls -alh

workflows:
  build-and-release:
    jobs:
      - build-resources