version: 2.1

orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@1.0

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - gh/release:
          notes-file: changelog.md
          tag: 1.0.0
          title: The initial release
          requires:
            - node/test
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main