version: 2.1

orbs:
  gh: circleci/github-cli@2.1.1

jobs:
  build-resources:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Package install
          command: npm install
      - run:
          name: Build all resources
          command: node index.js
      - run:
          name: Check generated files
          command: ls -alhR

workflows:
  build-and-release:
    jobs:
      - build-resources
      - gh/release:
          tag: 1.0.0
          title: release resources
          files: ./vatsim/sector.sct2
          requires: 
            - build-resources