version: 2.1

orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@1.0

jobs:
  build-all:
    steps:
      - checkout
      - run:
        name: Package install
        command: npm install

workflows:
  build:
    jobs:
      - build-all
      - gh/release:
          notes-file: changelog.md
          tag: 1.0.0
          title: The initial release
          requires:
            - node/test
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main
