version: 2.1

orbs:
  gh: circleci/github-cli@2.0

workflows:
  test-and-deploy:
    jobs:
      - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main
          notes-file: changelog.md
          tag: 1.0.0
          title: The initial release